### ISSUE TITLE
Add 'This file was generated' message

### ISSUE THREAD

**Issue by syxolk** [mp4096/indentex#12]
Similarly to `yarn.lock` files, one could prepend every `*_indentex.tex` with the following message to prevent accidental edits:

```
% ==============================================================
%
% THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
%
% ==============================================================
```

This functionality could be disabled with a command line option like `--disable-do-not-edit`.

**Comment by mp4096** [comment]
Sound good.
