### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by mp4096** [mp4096/indentex#29]
We have to look into [`cargo-deb`](https://github.com/mmstick/cargo-deb).

@syxolk Do you think dynamic linking to GNU `libc` is ok? Or should we compile with `musl`?

**Comment by mp4096** [comment]
Ugh, `musl` support seems to be Tier 2. Ok, then `gnu-libc`.

**Comment by syxolk** [comment]
What do you mean with tier 2? ripgrep also provides `musl` binaries.

**Comment by mp4096** [comment]
See [this overview](https://forge.rust-lang.org/platform-support.html) of supported platforms.

As I understand it, Tier 1 == works out of the box, Tier 2 == will probably work after some googling, Tier 3 == here be dragons.

**Comment by syxolk** [comment]
I wouldn't be so pessimistic about Tier 2 but I'm also ok with gnu-libc since it's pretty stable (compared to libc++).

*Update:* Especially for a debian package one can expect to have a decent version of libc preinstalled.

**Comment by mp4096** [comment]
> I wouldn't be so pessimistic about Tier 2

Sure, I mean we use `armv7-unknown-linux-gnueabihf` for the emoji stuff and it works like a charm (after some googling and configuring `cargo`). But stuff like `i586-pc-windows-msvc`?..

**Comment by syxolk** [comment]
What do you think about 32bit systems?

**Comment by mp4096** [comment]
I don't want to support them. Indentex is by no means a mission-critical piece of software, so hopefully nobody would want to install it on an old 32-bit system.

**Comment by syxolk** [comment]
Should we package a man file?

**Comment by mp4096** [comment]
No, I think `indentex --help` + web documentation should be enough for the first time being. When we have a spec (hoho) and a website (hohoho), we can think about manfiles.

**Comment by mp4096** [comment]
Finally, a working auto packaging and deployment! :sweat:
