### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by syxolk** [mp4096/indentex#35]
There seem to be three different approaches on how to build a [chocolatey package](https://github.com/chocolatey/choco/wiki/CreatePackages). They all need a `.nuspec` file containing the id, version, description and other stuff.

- Embed `indentex.exe` into the package and use the [auto-shim feature](https://chocolatey.org/docs/features-shim). Chocolatey will automatically move the executable to a folder where it is available on the path.
- Embed `indentex_*.msi` into the package and use [Install-ChocolateyInstallPackage](https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyInstallPackage) to install it. A `tools\chocolateyInstall.ps1` is needed.
- Download `indentex_*.msi` from GitHub during installation using [Install-ChocolateyPackage](https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyPackage). A `tools\chocolateyInstall.ps1` is needed.

All three variants seem to require elevated privileges because chocolatey uses `%ProgramData%`.

[On the difference between portable and installed packages.](https://github.com/chocolatey/choco/wiki/ChocolateyFAQs#what-distinction-does-chocolatey-make-between-an-installable-and-a-portable-application)

**Packaging**: By calling `choco pack` a `indentex.*.nupkg` is build.

**Deployment**: Requires an API key for chocolatey. Call `choco push` to publish on chocolatey.org. [This can be done automatically on appveyor.](https://github.com/StefanScherer/choco-otto/blob/master/appveyor.yml)

**Comment by syxolk** [comment]
**Benefits of the first approach:**
- No Registry Keys
- No additional modifications of `%PATH%`
- It should be possible to install it without administrator privileges

**Drawbacks of the first approach:**
- Indentex cannot be uninstalled via *Programs & Apps* (only via `choco uninstall`)
- One could also install the MSI package and may be confused

**Comment by syxolk** [comment]
Do you want to use your own chocolatey api key @mp4096 ?

**Comment by mp4096** [comment]
Uhm, I added some[thing](https://www.youtube.com/watch?v=v1EGxpzonk8), but I have no idea if it works.

**Comment by mp4096** [comment]
e1e6500cd6d612faf9b4e4f0717997e9e94d41d8

**Comment by syxolk** [comment]
> Uhm, I added something, but I have no idea if it works.

I just got lemon-grabbed 😆 .

**Comment by syxolk** [comment]
You probably need to add an artifact use its name instead of this regex: `/.*\.nupkg/` (I don't know if it finds the package.)

**Comment by mp4096** [comment]
huehuehue

**Comment by mp4096** [comment]
~~Is the path `.\packaging\windows_choco\package\indentex.nuspec`?~~

_Edit:_ I'm dumb.

**Comment by mp4096** [comment]
Oh shoot, what I'm thinking.

**Comment by mp4096** [comment]
`.\packaging\windows_choco\indentex.nuget`?

**Comment by syxolk** [comment]
For the current version it's `.\packaging\windows_choco\indentex.0.4.0.nupkg`.

**Comment by mp4096** [comment]
So, `/.\\packaging\\windows_choco\\indentex[.\w]+nupkg/`? Could you please verify if this regex works in PoSh?

**Comment by syxolk** [comment]
Better add it here:

```
artifacts:
  - path: 'packaging\windows_wix\*.msi'
    name: indentex_installer
```

and then reference the artifact's name.

**Comment by mp4096** [comment]
Oh, we already glob in artifacts. I dunno why, but I thought I must use a regex in the path specification.

**Comment by mp4096** [comment]
[Great success!](https://chocolatey.org/packages/indentex/0.4.0)

@syxolk Thank you for this! Do you want to open a PR?
