### ISSUE TITLE
Fix critical Choco issues

### ISSUE THREAD

**Issue by mp4096** [mp4096/indentex#40]
Request from Choco reviewer:

> Please also fix the following:
> - Include the license inside the package as LICENSE.txt
> - Add a VERIFICATION.txt file detailing how we can verify that the embedded binary file have been aquired from an official download location provided by the software authors (as well as the expected checksum).

I think it's better to specify files to be packaged explicitly, e.g. [like here](https://github.com/AdmiringWorm/chocolatey-packages/blob/08695592648d9ba1666dcc9609b902fb8241573b/automatic/enki/enki.nuspec#L38-L41).

And here's a [template](https://github.com/AdmiringWorm/chocolatey-packages/blob/08695592648d9ba1666dcc9609b902fb8241573b/automatic/enki/legal/VERIFICATION.txt) for the `VERIFICATION.txt` file.

@syxolk Could you please tackle both issues? I think we can create a template for `VERIFICATION.txt` and fill in the hash using some PoSh magic.

**Comment by syxolk** [comment]
We currently don't provide any exe for download that could be verified.

**Comment by mp4096** [comment]
@syxolk Thanks, I think we're done here.
