### ISSUE TITLE
Unwanted transpilation within listings

### ISSUE THREAD

**Issue by mp4096** [mp4096/indentex#45]
So I've just encountered this bug.

Consider the following Indentex code with the following listing:

```tex
\begin{lstlisting}
# TODO: Code stuff
def spam():
    return 0
\end{lstlisting}
```

I want it to be left unchanged. However, the Python comment gets transpiled:

```tex
\begin{lstlisting}
\TODO{Code stuff}
def spam():
    return 0
\end{lstlisting}
```

---

One obvious workaround would be to import listings from files instead of writing code directly in the Indentex document:

```tex
\lstinputlisting{./sources/spam.py}
```

Otherwise, I think there's just _no solution at all_ for this problem. We do promise that Indentex is a strict superset of LaTeX, but we just cannot promise it's a strict superset of all other stuff that can come up within `verbatim` or listing environments. :crying_cat_face:

**Comment by syxolk** [comment]
Can we introduce our own verbatim environment? Something like `#! lstinputlisting`

**Comment by mp4096** [comment]
Hm, we probably could, but then again we cannot exclude cases when the user wants to use the plain LaTeX environment. And I really do not want to force anyone use an Indentex command instead of plain LaTeX, plain LaTeX should always be a possibility.

**Comment by mp4096** [comment]
Ugh, re-reading the comment I just realise I sound like Trump, with all that repetitions. Sad!

**Comment by syxolk** [comment]
We gonna introduce this environment and the users gonna pay for it. It's
gonna be a **yuge** success.

But I see your point that it doesn't solve the superset problem.

Another idea would be to escape the number sign like this: `## Todo:`.
Identex will replace any occurrence of two consecutive number signs with
one.

**Comment by mp4096** [comment]
I'm pretty sure there are people out there who use `## TODO: ` in their Python code. Hey, [Yelp had an all-hardtabs Python codebase](https://eev.ee/blog/2016/06/04/converting-a-git-repo-from-tabs-to-spaces/) :scream:!

Also, see [obligatory xkcd reference](https://xkcd.com/1172/).

I think it's a real no-fix.

**Comment by syxolk** [comment]
Oh, and my first idea breaks included bash scripts with a shebang:
`#!/bin/bash`

**Comment by mp4096** [comment]
I recall a recent saying by a certain statesman:

> Now, I have to tell you, it's an unbelievably complex subject. Nobody knew health care could be so complicated

**Comment by mp4096** [comment]
Closing this issue as it's a defect-by-design. `¯\_(ツ)_/¯`
