### ISSUE TITLE
Transpilation of commands without arguments and children

### ISSUE THREAD

**Issue by syxolk** [mp4096/indentex#5]
I'm doing a beamer presentation and I want to write `\tableofcontents` and `\maketitle` in indentex. Is there any way to do this?

I tried `# tableofcontents` which is ignored by the transpiler and I tried `# tableofcontents:` that is transpiled to
```
\begin{tableofcontents}
\end{tableofcontents}
```

Sure, I could just use `\tableofcontents` but is there any better way?

**Comment by mp4096** [comment]
Uhm, actually this _is_ the way: Just write `\tableofcontents`.

You see, this was the philosophy behind `indentex`: Being a strict superset of LaTeX, it takes some burden off you, but if you want to, you can drop down to plain LaTeX anytime.

**Comment by syxolk** [comment]
Ok, that's fine for me. I just wanted to know if there is any hidden syntax.

**Comment by mp4096** [comment]
No, no hidden syntax...

Actually, there are some cases where `indentex` is plainly unusable, e.g. with `\includegraphics` and all of its curly braces arguments. Just drop down to LaTeX.

**Comment by mp4096** [comment]
Edit: It _is_ usable even in this case, just very weird.

**Comment by syxolk** [comment]
I'm currently fine with the given answers.
