### ISSUE TITLE
Silently ignored edge cases (e.g. missing colon)

### ISSUE THREAD

**Issue by syxolk** [mp4096/indentex#8]
I think its a bit strange to just ignore these cases while also not showing any warnings or errors:

```
# test
#test:
#test
```

I had at least two occasions on a single day when I had to look into the generated tex files to find out why my stuff doesn't work, only to see that I forgot a colon.

**Comment by mp4096** [comment]
Yep, this is a good one!

Also, all these three cases are invalid LaTeX syntax (however, e.g. `#1` is valid). So it's safe to assume that the user intended to type an indentex command.

---

This will require a good deal of refactoring. Essentially, a result of line parsing should be something like

```rust
enum Hashline {
    OpenEnv(Environment),
    PlainLine(String),
    HashlineWarning(String, String),
}
```

However, I wanted to refactor line parsing anyway, so...

**Comment by mp4096** [comment]
Let's move to #23 for this one.
